name: Train NFL Model
on:
  schedule:
    - cron: '0 9 * * 2'  # Tuesdays 09:00 UTC
  workflow_dispatch: {}

jobs:
  train:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt joblib
      - run: python -c "from app.train import train_and_save; train_and_save()"
      - name: Commit artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add app/model_artifacts/model.pkl app/model_artifacts/version.txt || true
          git commit -m "Update model artifacts [skip ci]" || echo "No changes"
          git push
